Updated for latest Rubies

diff --git a/mssql-server-linux-adapter-ci/Dockerfile b/mssql-server-linux-adapter-ci/Dockerfile
--- a/mssql-server-linux-adapter-ci/Dockerfile
+++ b/mssql-server-linux-adapter-ci/Dockerfile
@@ -4,7 +4,10 @@ FROM ruby:${TARGET_VERSION}-alpine
 
 LABEL maintainer="Wanderson Policarpo <wpolicarpo@gmail.com>"
 
-RUN apk add git make build-base linux-headers libressl-dev sqlite-dev tzdata freetds freetds-dev libpq postgresql-dev
+RUN apk add git make build-base linux-headers sqlite-dev tzdata freetds freetds-dev libpq postgresql-dev
+
+# Allow this package installation to fail for Rubies v3.1.3+
+RUN apk add git make libressl-dev || true
 
 RUN wget https://raw.githubusercontent.com/eficode/wait-for/master/wait-for \
     && chmod +x wait-for \
